name: Deploy to GitHub Pages using yarn

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: git
          GIT_PASS: ${{ secrets.DEPLOY_TOKEN }}
        run: yarn deploy
